changelog:
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - documentation
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
