name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/setup-python@v1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - run: pip install markdown-to-presentation

      - name: Create release
        run: markdown-to-presentation push --pages-branch release README.md LICENSE action.yml dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
